feat: add resource_data_source filter to date periods
City-of-Helsinki/hauki pull request #213
Opened 2024-05-06 08:56 UTC by nicobav

Makes possible to filter DatePeriods by linked resources data sources. Takes the ancestry into an account like it is in opening_hours enpoint

Refs HAUKI-633

2024-05-06 09:31 UTC, terovirtanen commented
**HAUKI-API branch is deployed to platta: https://hauki-pr213.api.dev.hel.ninja** :rocket::rocket::rocket:

2024-05-06 09:32 UTC, terovirtanen commented
## api tests result is __success__ for https://hauki-pr213.api.dev.hel.ninja :laughing::tada::tada::tada:

2024-05-06 10:52 UTC, danipran requested changes
Code looks fine. Need to add OpenAPI documentation. Here's the `data_source` filter's documentation as an example: https://github.com/City-of-Helsinki/hauki/blob/90587739d3997c8698f7644211f868676f723f77/hours/viewsets.py#L660-L665

2024-05-06 11:20 UTC, terovirtanen commented
**HAUKI-API branch is deployed to platta: https://hauki-pr213.api.dev.hel.ninja** :rocket::rocket::rocket:

2024-05-06 11:20 UTC, terovirtanen commented
## api tests result is __success__ for https://hauki-pr213.api.dev.hel.ninja :laughing::tada::tada::tada:

2024-05-07 07:56 UTC, terovirtanen commented
**HAUKI-API branch is deployed to platta: https://hauki-pr213.api.dev.hel.ninja** :rocket::rocket::rocket:

2024-05-07 07:57 UTC, terovirtanen commented
## api tests result is __success__ for https://hauki-pr213.api.dev.hel.ninja :laughing::tada::tada::tada:

2024-05-07 08:02 UTC, danipran approved these changes
LGTM! Not sure what's up with the Azure checks though 😅

2024-05-07 08:23 UTC, merged